repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.0
      hooks:
        - id: go-fmt
        - id: go-imports
        - id: no-go-testing
        - id: golangci-lint
        - id: go-unit-tests
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=90
          - --include='\.pyi?$'

          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --profile=black
